spring:
  thymeleaf:
    cache: false
    suffix: .html
    encoding: utf-8
  resources:
    static-locations: classpath:/resources/, classpath:/static/ ,classpath:/templates/
logging:
  level:
    root: info
    com.alibaba.excel: debug